import type { DieDefinition } from "./types";

export interface AppearancePreset {
  name: string;
  description: string;
  colorHex: string;
  pattern?: DieDefinition["pattern"];
  appearance: NonNullable<DieDefinition["appearance"]>;
}

export const APPEARANCE_PRESETS: AppearancePreset[] = [
  {
    name: "Crystal",
    description: "Clear crystalline die with strong refraction and sparkles.",
    colorHex: "#8bd6ff",
    appearance: {
      roughness: 0.05,
      metalness: 0.0,
      reflectivity: 0.7,
      transmission: 0.9,
      ior: 1.5,
      thickness: 1.0,
      attenuationDistance: 2,
      attenuationColor: "#8bd6ff",
      opacity: 1,
      clearcoat: 0.2,
      clearcoatRoughness: 0.1,
      sheen: 0.05,
      sheenColor: "#ffffff",
      sparkleIntensity: 0.4,
      sparkleCount: 120,
      sparkleColor: "#ffffff",
    },
  },
  {
    name: "Runic Glass",
    description: "Faintly glowing translucent violet with arcane depth.",
    colorHex: "#7b5df9",
    appearance: {
      roughness: 0.08,
      metalness: 0.05,
      reflectivity: 0.75,
      transmission: 0.92,
      ior: 1.48,
      thickness: 1.1,
      attenuationDistance: 2.2,
      attenuationColor: "#7b5df9",
      opacity: 1,
      clearcoat: 0.4,
      clearcoatRoughness: 0.08,
      sheen: 0.25,
      sheenColor: "#c184ff",
      sparkleIntensity: 0.35,
      sparkleCount: 140,
      sparkleColor: "#c184ff",
    },
  },
  {
    name: "Starforge",
    description: "Superheated cosmic metal with ember sparkle flecks.",
    colorHex: "#ff944d",
    appearance: {
      roughness: 0.22,
      metalness: 1.0,
      reflectivity: 0.85,
      transmission: 0.05,
      ior: 1.45,
      thickness: 0.3,
      attenuationDistance: 0.6,
      attenuationColor: "#ff944d",
      opacity: 1,
      clearcoat: 0.55,
      clearcoatRoughness: 0.18,
      sheen: 0.4,
      sheenColor: "#ffe2a8",
      sparkleIntensity: 0.6,
      sparkleCount: 110,
      sparkleColor: "#ffd17a",
    },
  },
  {
    name: "Void Opal",
    description: "Dark near-black core with iridescent spectral shimmer.",
    colorHex: "#0d0f14",
    appearance: {
      roughness: 0.18,
      metalness: 0.65,
      reflectivity: 0.7,
      transmission: 0.25,
      ior: 1.55,
      thickness: 0.7,
      attenuationDistance: 0.9,
      attenuationColor: "#302a40",
      opacity: 1,
      clearcoat: 0.7,
      clearcoatRoughness: 0.12,
      sheen: 0.5,
      sheenColor: "#7b5df9",
      sparkleIntensity: 0.55,
      sparkleCount: 150,
      sparkleColor: "#8bd6ff",
    },
  },
  {
    name: "Aurora Ice",
    description: "Icy translucent cyan with shifting aurora sparkle.",
    colorHex: "#95f3ff",
    appearance: {
      roughness: 0.04,
      metalness: 0.02,
      reflectivity: 0.85,
      transmission: 0.95,
      ior: 1.31,
      thickness: 1.3,
      attenuationDistance: 2.8,
      attenuationColor: "#95f3ff",
      opacity: 1,
      clearcoat: 0.25,
      clearcoatRoughness: 0.07,
      sheen: 0.35,
      sheenColor: "#8bd6ff",
      sparkleIntensity: 0.45,
      sparkleCount: 170,
      sparkleColor: "#ffffff",
    },
  },
  {
    name: "Obsidian",
    description: "Dark glassy volcanic sheen with subtle sparkles.",
    colorHex: "#1f2329",
    appearance: {
      roughness: 0.3,
      metalness: 0.7,
      reflectivity: 0.6,
      transmission: 0.0,
      ior: 1.45,
      thickness: 0.2,
      attenuationDistance: 0,
      attenuationColor: "#1f2329",
      opacity: 1,
      clearcoat: 0.5,
      clearcoatRoughness: 0.2,
      sheen: 0.1,
      sheenColor: "#4d5663",
      sparkleIntensity: 0.05,
      sparkleCount: 40,
      sparkleColor: "#ffc94d",
    },
  },
  {
    name: "Arcane Alloy",
    description: "Luminous enchanted metal with internal glow.",
    colorHex: "#6243f3",
    appearance: {
      roughness: 0.15,
      metalness: 0.9,
      reflectivity: 0.9,
      transmission: 0.15,
      ior: 1.4,
      thickness: 0.4,
      attenuationDistance: 1.2,
      attenuationColor: "#6243f3",
      opacity: 1,
      clearcoat: 0.6,
      clearcoatRoughness: 0.15,
      sheen: 0.3,
      sheenColor: "#ffc94d",
      sparkleIntensity: 0.25,
      sparkleCount: 90,
      sparkleColor: "#ffc94d",
    },
  },
  {
    name: "Ethereal",
    description: "Soft translucent pastel with floating motes.",
    colorHex: "#c184ff",
    appearance: {
      roughness: 0.1,
      metalness: 0.05,
      reflectivity: 0.6,
      transmission: 0.85,
      ior: 1.2,
      thickness: 0.6,
      attenuationDistance: 1.5,
      attenuationColor: "#c184ff",
      opacity: 1,
      clearcoat: 0.3,
      clearcoatRoughness: 0.25,
      sheen: 0.6,
      sheenColor: "#ffffff",
      sparkleIntensity: 0.5,
      sparkleCount: 160,
      sparkleColor: "#ffffff",
    },
  },
];
